### ISSUE TITLE
.git folder causing issues

### ISSUE THREAD

**Issue by carolynbump** [davidbilling/ember-cli-time-input#34]
Hello! I'm getting an issue while running npm install with version `0.4.1`. 

npm ERR! path /path/to/node_modules/ember-cli-time-input
npm ERR! code EISGIT
npm ERR! git /path/to/node_modules/ember-cli-time-input: Appears to be a git repo or submodule.
npm ERR! git /path/to/node_modules/ember-cli-time-input
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!   /path/to/.npm/_logs/2019-05-07T21_10_51_899Z-debug.log

My current work around is removing the node_modules folder and running `npm install` again, but was wondering if there was a better solution. Thanks!

**Comment by davidbilling** [comment]
@carolynbump Test version 0.4.2 it should be fixed!

**Comment by davidbilling** [comment]
@carolynbump Check out version 0.4.2 it should be fixed. =)

**Comment by davidbilling** [comment]
@carolynbump I'm closing this, should the problem persist then reopen this.
